# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d77be4de3b85c04e782be9296a7394dd16cff48b61c5df1a3a9fc6e65d91183a47bfcfd9da011109240734bef8e93afe84ad958dc117af7d397e3f34c05706e4

test:
  secret_key_base: 4cdc7690dec809711b16a8eb456c6152d509e2d3979b0ae7217641195a5ec2f5659d3f4f3c67690311d3968f9a9811b871f552f700ec3894fa365e35f413d2d2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
